sudo: false
language: ruby
rvm:
- 2.3.3
before_install: gem install bundler -v 1.14.6
addons:
  code_climate:
    repo_token:
      secure: "rzEVWgZoxVjhiqC3YwS3h2+aYLlA8FWnEuHfrvFS7kRbiOmA0h8STR7ajMS8K4nglen1UCo5uoH194UeGNeaVKUgADS/5Db4nadA9fQ8bOwpIyq9FpAA9IHqMkmQ7cHPJ6cYf4m0z25mVq4Wy7xJQQgBSSLJPGe9ZAHrE6sHd0LggsGM4St6IYqUXyf3Nshs36Mx70Kxi0YIh743frUAWDEXWv7VPtKjhLEBHN6ZB3F9W3HvwlRrpFKx5nJT6aeEdQxy+Day3cWel6a4j/VH2pm3LDGrkF9/WByu1ULCL5aUY46vKhAfVdWIucUc9ABi09+6xhI/mf8rcMUeK96qa/gCtE1f9Tn7bX8qolvJlOprJanYTiy2eOMjP0PCuWlOazW7oKoODIn74LHIZqz9Nk3zS9GmLsfc87M1BUM4ri9txoN8RlLu6mzR4Tf6D4uceDa8VlTJLCkxRyi/CDJDwIsmyWSeBHtoRn8AfeIhrZsmCCKq3giYUJawbprZB57aQ377f5r1ZasRrdUfpMXMw/6+YVqfnLzIaFfGsS2Jz5uddSIHww9fHYPEAy/0OIPG9AgmxrKFmi4DQe5O4I1wr3yuKRpMQtqJOBNS2vvryvoNmoMLLW2ThC5D1k2ig3/+FMMYNh8hsv6nYCz1o/EDnDxJ4bQAf9ulPAc/6feyqrk="
deploy:
  provider: rubygems
  api_key:
    secure: bVmhqQi0lR5UjoAPJsnhZPFcBYggOmQIlVZLV515US0qEwP7lDdOLY9arWLOubfd0Kr7UXp15a2JS5IiSMw9TcAKIiAeTAm9sbtha2R0qaPGJTnmE4pkn07aef3u/zg6zXdT8kj52142sket+fp//mJgKGPrlN41Tx+3xBC5+tZWQFOciUTKSz4+rpY9xgI6RECp+P5TLoopowCPvZpC3z4N5XVzzlvL+JMVnBEEc6+qXRNieasrwxzhOkY7qTj3x/tSDMjMnv+CMDUZrxVrwARZv1MJRL1alN/pCTsQr6e6iL7iBfvLL2Iy02GX1gRCi61MCJltjdPhQWm7mjV8+G4AwGVkrkJwMD5yBgt9g79lahLv9v0KIf8sxK7cMg0jYKW+apl8/hctZnkI9dy8eSw500F2obCg/iEznz3+t16NiMoBtD8Dk7Etg6DSnuiPzCGlRAq5zDIx5YRzl+1NyAmnGSgcmQkF82dKEkOyKUVLqWGJ9J+O0sFMnAOk0Lw5TaYjd2+1CzuXPmXnN+wgRxnCQKtZdVZ77PhL+NXihcvRHew8nkW0DRLe7k2qI1AQzQrSk0v13LE4mlm8ZhcOTDxbFqGn9+p7HmzWZX3dbxBb3dsuBUbhf1JBBvcbiar1CUf59LUzlJ8xADOOqbbb4uo4Z/TGb1y5UAXYSRuMpnQ=
  gem: bako
  on:
    tags: true
    repo: ayemos/bako
after_success:
  - bundle exec codeclimate-test-reporter
